/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.5/samples
 */

plugins {
    id("org.jetbrains.kotlinx.binary-compatibility-validator") version "0.14.0"
}

repositories {
    mavenCentral()
}

apiValidation {
}
